apps/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='index'),
    url(r'^p/(?P<id>.+)/(?P<slug>.+)/$', views.PostDetailView.as_view(),
                                                            name="detail"),
    url(r'^create/video/$', views.PostCreateView.as_view(),
                                                            name="create"), 
    url(r'^parse/$', views.CheckInfoYoutubeView.as_view(),
                                                            name="parse"),

]

bideox/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('apps.posts.urls', namespace='posts')),
    url(r'^channel/', include('apps.categories.urls', namespace='categories')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^admin/', include('apps.admin.urls', namespace='admin')),
]

apps/posts/models.py
from django.db import models

from apps.users.models import UserProfile
from apps.categories.models import Category

class Post(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    description = models.TextField(blank=True, default='')
    videoDurationFe = models.CharField(max_length=255)
    externalView = models.IntegerField(default=0, blank=True)
    dateCreate = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category)
    profile = models.ForeignKey(UserProfile, default=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        db_table = 'post'

apps/posts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import (ListView, DetailView, CreateView)
from django.conf import settings
from django.http import Http404

from apps.core.views import BaseView, LoginRequiredMixin
from apps.posts.models import Post
from apps.categories.models import Category

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

import requests
import json
import re
import isodate

class PostListView(BaseView, ListView):
    template_name = 'posts/index.html'
    model = Post
    paginate_by = 15 

    def get_queryset(self):
        return Post.objects.order_by('-dateCreate')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        info = {
            'info': {
                'title': 'Bideox - Funny bideo'
            }
        }
        context.update(info)
        return context

class PostDetailView(BaseView, DetailView):
    template_name = 'posts/detail.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        info = {
            'info': {
                'title': self.object.name
            }
        }
        context.update(info)
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('id', 'name', 'description', 
                'videoDurationFe', 'category',)
    template_name = 'posts/create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        info = {
            'info': {
                'title': 'Submit video - Bideox'
            }
        }
        context['category'] = Category.objects.all()
        context.update(info)
        return context

    def form_valid(self, form):
        post = form.save(commit=False)
        post.profile = self.request.user.profile
        post.slug = self.get_slug(form.cleaned_data['name'])
        post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('posts:index')

    def get_slug(self, str_input):
        str_input = str_input.lower().strip()

        str_input= re.sub(r'à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ',"a", str_input)
        str_input= re.sub(r'À|Á|Ạ|Ả|Ã|Â|Ầ|Ấ|Ậ|Ẩ|Ẫ|Ă|Ằ|Ắ|Ặ|Ẳ|Ẵ',"a", str_input)
        str_input= re.sub(r'è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ',"e", str_input)
        str_input= re.sub(r'È|É|Ẹ|Ẻ|Ẽ|Ê|Ề|Ế|Ệ|Ể|Ễ',"e", str_input)
        str_input= re.sub(r'ì|í|ị|ỉ|ĩ',"i", str_input)
        str_input= re.sub(r'Ì|Í|Ị|Ỉ|Ĩ',"i", str_input)
        str_input= re.sub(r'ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ',"o", str_input)
        str_input= re.sub(r'Ò|Ó|Ọ|Ỏ|Õ|Ô|Ồ|Ố|Ộ|Ổ|Ỗ|Ơ|Ờ|Ớ|Ợ|Ở|Ỡ',"o", str_input)
        str_input= re.sub(r'ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ',"u", str_input)
        str_input= re.sub(r'Ù|Ú|Ụ|Ủ|Ũ|Ư|Ừ|Ứ|Ự|Ử|Ữ',"u", str_input)
        str_input= re.sub(r'ỳ|ý|ỵ|ỷ|ỹ',"y", str_input)
        str_input= re.sub(r'Ỳ|Ý|Ỵ|Ỷ|Ỹ',"y", str_input)
        str_input= re.sub(r'đ|Đ',"d", str_input)
        str_input= re.sub(r'!|@|\$|%|\^|\*|\(|\)|\+|=|\&lt;|\&gt;|\?|\/|,|\.|\:|\'| |\"|\&amp;|\#|\[|\]|~',"-", str_input)
        str_input= re.sub(r'_',"-", str_input)
        str_input= re.sub(r' ',"-", str_input)
        str_input= re.sub(r'-+-',"-", str_input)
        str_input = str_input.strip('- ')
        return str_input
    
class CheckInfoYoutubeView(APIView):
    def get(self, request, format=None):
        url = request.GET.get('url', False)
        if url:
            data = self.get_info(url)
            return Response(data)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)

    def get_info(self, url):
        m = self.youtube_url_validation(url)
        if m:
            recv = self.youtube_info_video(m)
            if recv:
                data = {
                    'status': True,
                    'message': 'Get youtube info success',
                    'data': recv
                }
            else:
                data = {
                    'status': False,
                    'message': 'Get youtube info fail',
                }
            return data
        else:
            data = {
                'status': False,
                'message': 'Youtube url not valid'
            }
            return data

    def youtube_url_validation(self, url):
        youtube_regex = (
            r'(https?://)?(www\.)?'
            '(youtube|youtu|youtube-nocookie)\.(com|be)/'
            '(watch\?v=|embed/|v/|.+\?v=)?([^&=%\?]{11})'
        )

        youtube_regex_match = re.match(youtube_regex, url)
        if youtube_regex_match:
            return youtube_regex_match.group(6)

        return youtube_regex_match

    def youtube_info_video(self, youtube_id):
        try:        
            url_request = "https://www.googleapis.com/youtube/v3/videos?part=snippet%2C+contentDetails&id="\
                                                             + youtube_id + "&key=" + settings.YOUTUBE_API_KEY
            response = requests.get(url_request)
            video_detail = json.loads(response.text)
            video_detail = video_detail['items'][0]
            data = {
                'id': youtube_id,
                'name': video_detail['snippet']['title'],
                'description': video_detail['snippet']['description'],
                'videoDurationFe': video_detail['contentDetails']['duration']            
            }
            dur = isodate.parse_duration(data['videoDurationFe'])
            data['videoDurationFe'] = str(dur)
            return data
        except:
            return False
        

templates/posts/create.html
{% extends 'layout/base.html' %}
{% load staticfiles %}

{% block css %}
{% endblock %}

{% block content_top %}
    <div class="alert-message-container">
        <div class="alert-message-container">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div id="jsid-alert-message" class="alert alert-success hide" style="margin-top: 10px;">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <span>Fetching data from source ...</span>
                        </div>
                        <!-- alert -->
                    </div>
                    <!-- / col-md-12 -->
                </div>
                <!-- / row -->
            </div>
            <!-- / container -->
        </div>
    </div>
{% endblock %}

{% block content_left %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="page-header">
                    <h1>Submit video</h1>
                </div>
            </div>
            <!-- / col-md-12 -->
        </div>

        <div class="row">
            <div class="col-md-4 col-md-push-8 hidden-sm hidden-xs">
                <div class="user-upload-preview">
                    <div class="responsivewrapper">
                        <p class=""><iframe src="" allowfullscreen="" autoplay="0" frameborder="0"></iframe></p>
                    </div>
                    <!-- responsivewrapper -->
                </div>
                <!-- / user-upload-preview -->
            </div>
            <!-- / col-md-4-->
            <div class="col-md-8 col-md-pull-4">
                <div class="user-upload-form">
                    <form class="form-user-upload" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control" id="id_video" name="id" value="" type="hidden">
                            <input class="form-control" id="id_videoDurationFe" name="videoDurationFe" value="" type="hidden">

                            <input id="id_url" class="form-control" placeholder="Paste Video Link..." type="url">
                            {% if form.id.errors %}
                                <div id="message_id" class="alert alert-danger">
                                    {{ form.id.errors }}
                                </div>
                            {% endif %}
                            <!-- / alert -->
                        </div>
                        <!-- / form-group -->
                        <div class="form-group">
                            <input id="id_name" name="name" class="form-control badge-form-check-object" placeholder="Name" type="text">
                            {% if form.name.errors %}
                                <div class="alert alert-danger">
                                    {{ form.name.errors }}
                                </div>
                            {% endif %}
                        </div>
                        <!-- / form-group -->
                        <div class="form-group">
                            <textarea name="description" id="id_description" class="form-control" rows="8" placeholder="Description (Optional)"></textarea>
                        </div>
                        <!-- / formgroup -->
                        <div class="form-group">
                            <label>Channel:</label>
                            <p>
                                {% for cat in category %}
                                <label class="radio-inline">
                                    <input name="category" value="{{ cat.id }}" type="radio"> {{ cat.name }}
                                </label>
                                {% endfor %}
                            </p>
                            {% if form.category.errors %}
                                <div class="alert alert-danger">
                                    {{ form.category.errors }}
                                </div>
                            {% endif %}
                        </div>
                        <!-- / form-group -->
                        <div class="btn-container">
                            <button class="btn btn-primary badge-evt" type="submit">Save</button>
                        </div>
                        <!-- / btn-container -->
                    </form>
                </div>
                <!-- / user-upload-form -->
            </div>
            <!-- / col-md-8 -->
        </div>
    </div>
{% endblock %}

{% block content_right %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        var is_busy = False;
        $("#id_url").on('keyup keypress blur change', function() {
            if (!is_busy) {
                is_busy = True;
                event();
            };
        });

        function event() {
            var str = $('#id_url').val();
            if (str) {
                console.log(new Date()); 
                $('#jsid-alert-message').addClass('alert-success');
                $('#jsid-alert-message span').text('Fetching data from source ...');
                $('#jsid-alert-message').removeClass('hide');

                $.get("/parse", { url: str })
                .done(function(data) {
                    is_busy = False;
                    if (data['status']) {
                        set_value(data['data']);
                    } else {
                        $('#jsid-alert-message span').text('Not valid video url');
                        $('#jsid-alert-message').removeClass('alert-success');
                        $('#jsid-alert-message').addClass('alert-danger');
                        clear_all();
                        setTimeout(function() {
                            $('#jsid-alert-message').addClass('hide');
                        }, 3000);
                    };
                });
            } else {

            };
        };

        function set_value(data) {
            $('#id_video').val(data.id);
            $('#id_name').val(data.name);
            $('#id_videoDurationFe').val(data.videoDurationFe);
            $('#id_description').val(data.description);
        };

        function clear_all() {
            $('#id_url').val('');
            $('#id_video').val('');
            $('#id_name').val('');
            $('#id_videoDurationFe').val('');
            $('#id_description').val('');  
        };
    </script>
{% endblock %}

templates/posts/detail.html
{% extends 'layout/base.html' %}
{% load staticfiles %}
{% load templatetags_posts %}

{% block css %}
    <link rel="stylesheet" href="{% static 'frontend/css/jarvis-lib.min.css' %}">
{% endblock %}

{% block content_top %}
    <div class="stage">
	    <div class="container">
	        <div class="row">
	            <div class="badge-stage-left col-md-8">
	                <div class="post-list-t1">
	                    <div class="badge-video-cover item clearfix">
	                        <iframe allowfullscreen="true" src="https://www.youtube.com/embed/{{ post.id }}?autohide=1&amp;autoplay=0&amp;controls=1&amp;modestbranding=0&amp;rel=0&amp;showinfo=0&amp;theme=dark&amp;vq=hd720&amp;iv_load_policy=3" frameborder="0" width="100%" height="380"></iframe>
	                    </div>
	                </div>

	                <div class="youtube-bar clearfix">
	                    <div class="pull-left">
	                        <div class="widget">
	                            <h4 class="cta">
	                                <b>Subscribe </b>
                                </h4>
                                <ul class="social-love-button nav navbar-nav navbar-right" style="margin-left: 10px;">
                                    <li class="facebook">
                                        <div class="fb-like" data-href="https://www.facebook.com/bideox" data-width="90" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
                                    </li>
                                </ul>
	                        </div>
	                    </div>

	                    <div class="pull-right hidden-xs">
	                        
	                    </div>
	                </div>

                    <div id="jsid-post-single-shares-bottom-container">
                        <div class="post-bar">
                            <!--
                            <div class="btn-container clearfix">
                                <div class="pull-left hidden-xs hidden-sm">
                                    <a class="badge-upvote-btn badge-evt btn btn-invert btn-lg" data-evt="PostAction,Vote,Upvote" href="javascript:void(0);"><i class="fa fa-arrow-up"></i></a>

                                    <a class="badge-downvote-btn badge-evt btn btn-invert btn-lg" data-evt="PostAction,Vote,Downvote" href="javascript:void(0);"><i class="fa fa-arrow-down"></i>
                                    </a>
                                </div>

                                <div class="pull-right hidden-xs hidden-sm">
                                    
                                </div>
                            </div>
                            -->
                        </div>
                    </div>
	            </div>

	            <div class="col-md-4 hidden-xs hidden-sm">
	                <div class="playlist" style="height: 440px;">
	                    <div class="viewport" style="height: 440px;">
	                        <div class="overview" style="top: -78.859375px;">
	                            <div class="badge-post-grid-container post-list-t1 horizontal sidebar col-4">
	                            	{% for obj in rand %}
		                                <div class="badge-grid-item">
		                                    <div class="item clearfix post-playlist ">
		                                        <a class="img-container" href="{% url 'posts:detail' obj.id obj.slug %}">
		                                            <div class="responsivewrapper" style="background: url(&#39;https://i.ytimg.com/vi/{{ obj.id }}/default.jpg&#39;) center; background-size: cover;"></div>
		                                        </a>
		                                        <div class="info">
		                                            <a class="title" href="{% url 'posts:detail' obj.id obj.slug %}">
		                                                <h4>{{ obj.name }}</h4>
		                                            </a>
		                                            <div class="meta">
		                                                <p>{{ obj.videoDurationFe }}</p>
		                                            </div>
		                                        </div>
		                                    </div>
		                                </div>
	                                {% endfor %}
	                            </div>
	                            <!--end .post-list-t1-->
	                        </div>
	                    </div>
	                </div>
	            </div>
	        </div>
	        <!-- / row -->
	    </div>
	    <!-- / container -->
	</div>
{% endblock %}

{% block content_left %}
	<div class="col-md-8">
        <article class="article-t1">
            <div id="jsid-post-single-meta-container">
                <header class="header-t1">
                    <h1>{{ post.name }} <small>{{ post.videoDurationFe }}</small></h1>
                    <p class="meta">
                        <b>{{ post.externalView|format_number }}</b> views
                    </p>
                    <!--<p id="jsid-description">{{ post.description }}.</p>-->
                </header>
            </div>
        </article>
        <div id="comment" class="block-comment">
            <div class="badge-comment-content fb-comments-responsive">
                <div class="fb-comments" data-href="http://bideox.com/p/{{ post.id }}/{{ post.slug }}" data-colorscheme="light" data-numposts="15" data-width="100%"></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/posts/index.html
{% extends 'layout/base.html' %}

{% block content_top %}
    <div class="post-list-t1 cover">
        <div class="badge-post-grid-container row no-gutter">
            {% for obj in object_list %}
                {% if forloop.counter <= 5 %}
                    <div class="badge-grid-item">
                        <div class="col-md-3">
                            <div class="item">
                                <a class="img-container" href="{% url 'posts:detail' obj.id obj.slug %}">
                                    <div class="responsivewrapper" style="background: url(&#39;https://i.ytimg.com/vi/{{ obj.id }}/hqdefault.jpg&#39;) center; background-size: cover;"></div>
                                </a>
                                <div class="info">
                                    <a class="title" href="{% url 'posts:detail' obj.id obj.slug %}">
                                        <h4>{{ obj.name }}</h4>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block content_left %}
    <div class="col-md-8">
        <div class="main">
            <div class="badge-post-grid-container post-list-t1 horizontal col-4">
                {% for obj in object_list %}
                    {% if forloop.counter > 5 %}
                        <div class="badge-grid-item">
                            <div class="item twoColumn-left clearfix">
                                <a class="img-container" href="{% url 'posts:detail' obj.id obj.slug %}">
                                    <div class="responsivewrapper" style="background: url(&#39;https://i.ytimg.com/vi/{{ obj.id }}/mqdefault.jpg&#39;) center; background-size: cover;"></div>
                                </a>
                                <div class="info">
                                    <a class="title" href="{% url 'posts:detail' obj.id obj.slug %}">
                                        <h4>{{ obj.name }} <small>{{ obj.videoDurationFe }}</small></h4>
                                    </a>
                                    <div class="meta">
                                        <p>{{ obj.description }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>

        <div class="paging-buttons">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="previous"><span aria-hidden="true">&larr;</span> Previous</a>
            {% else %}
                <a href="#" class="previous disabled" onclick="return false;"><span aria-hidden="true">&larr;</span> Previous</a>
            {% endif %}
            
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="next">Next <span aria-hidden="true">&rarr;</span></a>
            {% endif %}
        </div>
    </div>
{% endblock %}
