apps/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^signup/$', views.SignupUserView.as_view(), name='signup'),
    url(r'^login/$', views.LoginUserView.as_view(), name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', 
                        {'next_page': '/'}, name='logout'),
]

bideox/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('apps.posts.urls', namespace='posts')),
    url(r'^channel/', include('apps.categories.urls', namespace='categories')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^admin/', include('apps.admin.urls', namespace='admin')),
]

apps/users/models.py
from django.db import models
from django.conf import settings

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                primary_key=True, related_name='profile')

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'UserProfile'
        verbose_name_plural = 'UserProfiles'
        db_table = 'user_profile'

apps/users/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.urlresolvers import reverse_lazy, reverse
from django.apps import apps as django_apps
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import (
    CreateView, FormView,
)
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
)

from apps.core.views import BaseView

class SignupUserView(BaseView, CreateView):
    model = django_apps.get_model(settings.AUTH_USER_MODEL)
    form_class = UserCreationForm
    template_name = 'users/signup.html'

    def get_success_url(self):
        return reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        context = super(SignupUserView, self).get_context_data(**kwargs)
        info = {
            'info': {
                'title': 'Signup'
            }
        }
        context.update(info)
        return context

    def form_valid(self, form):
        self.object = form.save()
        messages.success(self.request, "You've signed up successfully,\
                            You can log in now.")
        return HttpResponseRedirect(self.get_success_url())

class LoginUserView(BaseView, FormView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next', False)
        info = {
            'info': {
                'title': 'Login'
            }
        }
        context.update(info)
        return context

    def get_success_url(self):
        nextlink = self.request.POST.get('next', False)
        if nextlink:
            return nextlink
        return reverse_lazy('posts:index')

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super().form_valid(form)

templates/users/login.html
{% extends 'layout/base.html' %}

{% load staticfiles %}

{% load socialaccount %}
{% providers_media_js %}

{% block css %}
    <link href="{% static 'frontend/css/gag.min.css' %}" media="screen,projection" rel="stylesheet" type="text/css">    
{% endblock %}

{% block content_top %}
{% endblock %}

{% block content_left %}
    <div class="badge-page page">
        <section id="signup">
            <h2>Login</h2>
            <p class="lead">Connect with a social network</p>
            <div class="social-signup">
                <!--<a class="btn-connect-option facebook badge-facebook-connect" href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook</a>-->

                <a class="btn-connect-option facebook badge-facebook-connect" href="{% provider_login_url "facebook" method="oauth2" %}">Facebook</a>

                <span class="badge-gplus-connect">
                    <a class="btn-connect-option google-plus" href="#">Google</a>
                </span> 
            </div>

            <form id="login-email" class="badge-login-form" action="" method="POST">
                {% csrf_token %}
                <p class="lead">Log in with your email address </p>
                <div class="field">
                    <label>Username</label>
                    <input type="text" name="username" value="{{ form.username.value|default_if_none:'' }}" autofocus="autofocus">                    
                </div>
                <div class="field">
                    <label>Password</label>
                    <input type="password" name="password" value="">
                    {% if form.non_field_errors %}
                        <p class="error-message red">Wrong Username/Email and password combination.</p>
                    {% endif %}
                </div>
                <div class="btn-container">
                    <input class="btn left" type="submit" value="Log in">
                    <a class="forgot-password" href="{% url 'users:signup' %}">Sign up</a>                    
                </div>
            </form>
        </section>
    </div>
{% endblock %}

{% block content_right %}
{% endblock %}

{% block js %}
{% endblock %}

templates/users/signup.html
{% extends 'layout/base.html' %}

{% load staticfiles %}

{% load socialaccount %}
{% providers_media_js %}

{% block css %}
    <link href="{% static 'frontend/css/gag.min.css' %}" media="screen,projection" rel="stylesheet" type="text/css">    
{% endblock %}

{% block content_top %}
{% endblock %}

{% block content_left %}
    <div class="badge-page page">
        <section id="signup">
            <h2>Signup</h2>
            <p class="lead">Connect with a social network</p>
            <div class="social-signup">
                <!--<a class="btn-connect-option facebook badge-facebook-connect" href="{% provider_login_url "facebook" method="js_sdk" %}">Facebook</a>-->

                <a class="btn-connect-option facebook badge-facebook-connect" href="{% provider_login_url "facebook" method="oauth2" %}">Facebook</a>

                <span class="badge-gplus-connect">
                    <a class="btn-connect-option google-plus" href="#">Google</a>
                </span> 
            </div>

            <form id="login-email" class="badge-login-form" action="" method="POST">
                {% csrf_token %}

                <p class="lead">Log in with your username </p>
                <div class="field">
                    <label>Username</label>
                    <input type="text" name="username" value="{{ form.username.value|default_if_none:'' }}" autofocus="autofocus">
                    {% if form.username.errors %}
                        {{ form.username.errors }}
                    {% endif %}
                </div>
                <div class="field">
                    <label>Password</label>
                    <input type="password" name="password1" value="{{ form.password1.value|default_if_none:'' }}">
                    {% if form.password1.errors %}
                        {{ form.password1.errors }}
                    {% endif %}
                </div>

                <div class="field">
                    <label>Re Password</label>
                    <input type="password" name="password2" value="">
                    {% if form.password2.errors %}
                        {{ form.password2.errors }}
                    {% endif %}
                </div>   

                <div class="btn-container">
                    <input class="btn left" type="submit" value="Sign up">
                    <a class="forgot-password" href="{% url 'users:login' %}">Login</a>                    
                </div>
            </form>
        </section>
    </div>
{% endblock %}

{% block content_right %}
{% endblock %}

{% block js %}
{% endblock %}