apps/admin/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^login/', views.LoginView.as_view(), name='login'),

    url(r'^category/$', views.CategoryListView.as_view(), 
                                                    name='category_list'),
    url(r'^category/create/$', views.CategoryCreateView.as_view(),
                                                name='category_create'),
    url(r'^category/update/(?P<pk>[0-9]+)/$',
                                        views.CategoryUpdateView.as_view(),
                                                name='category_update'),
    url(r'^category/delete/(?P<pk>[0-9]+)/$',
                                        views.CategoryDeleteView.as_view(), 
                                                name='category_delete'),

    url(r'^post/$', views.PostListView.as_view(), name='post_list'),
    url(r'^post/create/$', views.PostCreateView.as_view(),
                                            name='post_create'),
    url(r'^post/update/(?P<pk>.+)/$', views.PostUpdateView.as_view(),
                                            name='post_update'),
    url(r'^post/delete/(?P<pk>.+)/$', views.PostDeleteView.as_view(),
                                            name='post_delete'),
]

apps/categories/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^(?P<pk>[0-9]+)-(?P<slug>[\w-]+)/$',
                    views.CategoryListView.as_view(), name='list') 
]

apps/posts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='index'),
    url(r'^p/(?P<id>.+)/(?P<slug>.+)/$', views.PostDetailView.as_view(),
                                                            name="detail"),
    url(r'^create/video/$', views.PostCreateView.as_view(),
                                                            name="create"), 
    url(r'^parse/$', views.CheckInfoYoutubeView.as_view(),
                                                            name="parse"),

]

apps/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^signup/$', views.SignupUserView.as_view(), name='signup'),
    url(r'^login/$', views.LoginUserView.as_view(), name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', 
                        {'next_page': '/'}, name='logout'),
]

bideox/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('apps.posts.urls', namespace='posts')),
    url(r'^channel/', include('apps.categories.urls', namespace='categories')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^admin/', include('apps.admin.urls', namespace='admin')),
]

templates/layout/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>{{ info.title }}</title>
        <link rel="icon" href="{% static 'frontend/images/favicon.ico' %}" />
        <link rel="image_src" href="{% static 'frontend/images/logo.png' %}" / >
        <meta http-equiv="Cache-control" content="public">        
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="theme-color" content="#ffffff">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="You are looking at the bideox.com! bideox.com is the easiest way to have fun!">
        <meta name="keywords" content="bideox,tv,video,jokes,interesting,cool,fun collection,fun portfolio, admire,fun,humor,humour,just for fun,笑圖,笑片,搞笑,笑話">
        
        <!-- <link rel="stylesheet" href="{% static 'frontend/css/bootstrap.min.css' %}"> -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        
        <link rel="stylesheet" href="{% static 'frontend/css/jarvis-main.min.css' %}">
        <link rel="stylesheet" href="{% static 'frontend/css/jarvis-tv.min.css' %}">        
        <link rel="stylesheet" href="{% static 'frontend/css/jarvis-theme-2.min.css' %}">
        <link rel="stylesheet" href="{% static 'frontend/css/custom.css' %}">

        <link rel="stylesheet" href="{% static 'frontend/css/jarvis-lib.min.css' %}">

        {% block css %}
        {% endblock %}
    </head>

    <body>
        {% include 'layout/nav.html' %}

        {% include 'layout/menu.html' %}

        <section class="content">
            {% block content_top %}
            {% endblock %}

            <div class="listview">
                <div class="container">
                    <div class="row">
                        {% block content_left %}
                        {% endblock %}

                        {% block content_right %}
                            <div class="col-md-4 hidden-sm hidden-xs">
                                <div class="sidebar">
                                    <div class="section-header">
                                        <h3>Most Popular</h3>
                                    </div>

                                    <div class="post-list-t1">
                                        <div class="badge-post-grid-container">
                                            {% for obj in most_popular %}
                                                <div class="badge-grid-item badge-post-item-aqNN6y">
                                                    <div class="item clearfix r-17-7">
                                                        <a class="img-container" href="{% url 'posts:detail' obj.id obj.slug %}">
                                                            <div class="responsivewrapper" style="background: url(&#39;https://i.ytimg.com/vi/{{ obj.id }}/hqdefault.jpg&#39;) center; background-size: cover;"></div>
                                                        </a>
                                                        <div class="info">
                                                            <a class="title" href="{% url 'posts:detail' obj.id obj.slug %}">
                                                                <h4>{{ obj.name }} <small>{{ obj.videoDurationFe }}</small></h4>
                                                            </a>
                                                            <div class="meta">
                                                                <p>{{ obj.description }}.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endblock %}                        
                    </div>
                </div>
            </div>
        </section>
        
        {% include 'layout/footer.html' %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <script>
          window.fbAsyncInit = function() {
            FB.init({
              appId      : '159740451027848',
              xfbml      : true,
              version    : 'v2.4'
            });
          };

          (function(d, s, id){
             var js, fjs = d.getElementsByTagName(s)[0];
             if (d.getElementById(id)) {return;}
             js = d.createElement(s); js.id = id;
             js.src = "http://connect.facebook.net/en_US/sdk.js";
             fjs.parentNode.insertBefore(js, fjs);
           }(document, 'script', 'facebook-jssdk'));
        </script>

        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-66675447-1', 'auto');
          ga('send', 'pageview');

        </script>

        {% block js %}
            
        {% endblock %}        
    </body>
</html>

templates/layout/footer.html
{% load staticfiles %}

<!-- Footer -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="links">
                    BideoX.com © 2015
                </p>
            </div>
        </div>
    </div>
</footer>

templates/layout/menu.html
<div class="channel-bar">
    <div class="container">
        <ul class="nav nav-tabs channel">
        	<li {% if active == 'home' %} class="active" {% endif %}>
                <a href="/">Home</a>
            </li>
        	{% for obj in category %}
	            <li {% if active == obj.slug.lower %} class="active" {% endif %}>
                    <a href="{% url 'categories:list' obj.id obj.slug.lower %}">{{ obj.name }}</a>
	            </li>
            {% endfor %}
        </ul>
    </div>
</div>

templates/layout/nav.html
{% load staticfiles %}

<nav class="navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
        <div class="col-lg-4">
            <a href="/" class="badge-evt">
            	<img src="{% static 'frontend/images/logo.png' %}" height="50px" style="margin: 10px 5px;" />
            </a>
        </div>

        <div class="col-lg-8">
            {% if request.user.is_authenticated %}
                <ul class="badge-account-me nav-account nav navbar-nav navbar-right">
                    <li class="dropdown keepstyle">
                        <a href="#" class="badge-evt dropdown-toggle" data-toggle="dropdown">
                            <div class="img-container">
                                <img class="badge-account-avatar" width="34" height="34" src="{% static 'frontend/images/anon.png' %}">
                            </div>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="badge-evt" href="#">Settings</a></li>
                            <li><a class="badge-evt badge-account-logout" href="{% url 'users:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="badge-user-functions">
                    <li>                        
                        <a class="badge-upload-btn upload-btn badge-evt" style="padding: 22px 0;" href="{% url 'posts:create' %}"><i class="fa fa-plus fa-lg"></i></a>
                    </li>
                </ul>
            {% else %}
                <ul class="badge-user-functions">
                    <li id="jsid-notification-toggle" class="dropdown">
                        <a href="{% url 'users:login' %}" class="badge-account-login badge-evt btn btn-primary navbar-btn pull-right visitor-signin-btn">Sign in</a>
                        <a class="badge-upload-btn upload-btn badge-evt" href="{% url 'posts:create' %}"><i class="fa fa-plus fa-lg"></i></a>
                    </li>
                </ul>
            {% endif %}
        </div>        
    </div>
</nav>